// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg48qXeav1PpFN0Hv7SKpnnjYXv8McAFY',
    appId: '1:753718784296:web:4ce0721db06643551ee01d',
    messagingSenderId: '753718784296',
    projectId: 'letsmeet-74d21',
    authDomain: 'letsmeet-74d21.firebaseapp.com',
    databaseURL: 'https://letsmeet-74d21-default-rtdb.firebaseio.com',
    storageBucket: 'letsmeet-74d21.appspot.com',
    measurementId: 'G-YQ4NETL40T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1DEB3mwWvppTOqhZvUbBigde2dB0ocI',
    appId: '1:753718784296:android:accd80d98310ecdc1ee01d',
    messagingSenderId: '753718784296',
    projectId: 'letsmeet-74d21',
    databaseURL: 'https://letsmeet-74d21-default-rtdb.firebaseio.com',
    storageBucket: 'letsmeet-74d21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtN55PuogwoJZhbdTtI-0z6pwefIasxA',
    appId: '1:753718784296:ios:31a89d225294b2b31ee01d',
    messagingSenderId: '753718784296',
    projectId: 'letsmeet-74d21',
    databaseURL: 'https://letsmeet-74d21-default-rtdb.firebaseio.com',
    storageBucket: 'letsmeet-74d21.appspot.com',
    iosBundleId: 'com.example.jenkinstest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtN55PuogwoJZhbdTtI-0z6pwefIasxA',
    appId: '1:753718784296:ios:31a89d225294b2b31ee01d',
    messagingSenderId: '753718784296',
    projectId: 'letsmeet-74d21',
    databaseURL: 'https://letsmeet-74d21-default-rtdb.firebaseio.com',
    storageBucket: 'letsmeet-74d21.appspot.com',
    iosBundleId: 'com.example.jenkinstest',
  );
}
