# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  
  # Prod Release Lane
  desc "My awesome app"
    lane :distributeProd do
        build_android_app(task: "assemble",
        # build_android_app(task: "assemble",
        # flavor: "prod",
        build_type: "Release")
        # build_android_app is a built-in fastlane action.
        firebase_app_distribution(
            app: "1:753718784296:android:accd80d98310ecdc1ee01d",
            testers: "aayushkedawat@gmail.com",
            release_notes: "Test release notes",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        )
    end
  # # UAT Release Lane
  # desc "My awesome app"
  #   lane :distributeUAT do
  #       build_android_app(task: "assemble",
  #       # build_android_app(task: "assemble",
  #       flavor: "uat",
  #       build_type: "Release")
  #       # build_android_app is a built-in fastlane action.
  #       firebase_app_distribution(
  #           app: "1:273606157413:android:99fe8e1bee4b519e84928c",
  #           groups_file: "../uat-users-android.txt",
  #           release_notes_file: "../release_notes.txt",
  #           android_artifact_type: "APK",
  #           android_artifact_path: "../build/app/outputs/apk/uat/release/app-uat-release.apk",
  #       )
  #   end
  # # QA Release Lane
  # desc "My awesome app"
  #   lane :distributeQA do
  #       build_android_app(task: "assemble",
  #       # build_android_app(task: "assemble",
  #       flavor: "qa",
  #       build_type: "Release")
  #       # build_android_app is a built-in fastlane action.
  #       firebase_app_distribution(
  #           app: "1:273606157413:android:5a54331fc49bcc7584928c",
  #           groups_file: "../qa-users-android.txt",
  #           release_notes_file: "../release_notes.txt",
  #           android_artifact_type: "APK",
  #           android_artifact_path: "../build/app/outputs/apk/qa/release/app-qa-release.apk",
  #       )
  #   end
  # # Dev Release Lane
  # desc "My awesome app"
  #   lane :distributeDev do
  #       build_android_app(task: "assemble",
  #       # build_android_app(task: "assemble",
  #       flavor: "dev",
  #       build_type: "Release")
  #       # build_android_app is a built-in fastlane action.
  #       firebase_app_distribution(
  #           app: "1:273606157413:android:995a711d9713f6ba84928c",
  #           groups_file: "../dev-users-android.txt",
  #           release_notes_file: "../release_notes.txt",
  #           android_artifact_type: "APK",
  #           android_artifact_path: "../build/app/outputs/apk/dev/release/app-dev-release.apk",
  #       )
  #   end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
